### ISSUE TITLE
Theming Disa

### ISSUE THREAD

**Issue by HammyHavoc** [gabrielelucci/greyscale-cmte#12]
Somewhat of a noob to themes, but eager to learn. I'm interested in adding support for Disa, the source of which is available on GitHub. Would be interested in seeing how you conclude what the item names for each element are, i.e. android:navigationBarColor in the calculator app when a quick scan through the source for Disa doesn't reveal much info on colors other than changing the RGB LED notification color or adding a specific color for different services.

**Comment by gabrielelucci** [comment]
What is Disa?

**Comment by HammyHavoc** [comment]
Disa.im is a unified messaging app for Android.

_HammyHavoc // CEO of Split An Atom_

**Comment by gabrielelucci** [comment]
Not interested in theming 3rd party apps. My theme it's just for system apps and very few Gapps.
