### ISSUE TITLE
Google Play Store: Italian description for endusers with German as default language

### ISSUE THREAD

**Issue by thopiekar** [gabrielelucci/greyscale-cmte#18]
Just noticed since I bought your theme that I always get a Italian description. I think if there is no German translation you should at least show a english one.
The reason could be that you've set your native language as default for your app.

Regards

**Comment by gabrielelucci** [comment]
What do you mean? Where do you see Italian description? The only thing I can think of it's the Play Store screenshots, which are taken from my device, which ha default language set to Italian.

**Comment by thopiekar** [comment]
![screenshot_20160823-211939](https://cloud.githubusercontent.com/assets/1847437/17906453/b18be398-6977-11e6-8824-0fc9db06b0fe.png)

**Comment by gabrielelucci** [comment]
Okay, for some reason Italian was set as default language. Now it's set to english (en-gb).

Thank you for reporting!

**Comment by thopiekar** [comment]
Just happens 😉 No problem!
