### ISSUE TITLE
Request: crDroid support

### ISSUE THREAD

**Issue by sm4tik** [gabrielelucci/greyscale-cmte#5]
Currently only the main crDroid icon missing in settings

https://github.com/crdroidandroid/android_packages_apps_Settings/blob/6.0.0/res/xml/dashboard_categories.xml
line 96 ->

https://github.com/crdroidandroid/android_packages_apps_Settings/blob/6.0.0/res/drawable/ic_settings_system.xml

**Comment by gabrielelucci** [comment]
Thank you! I'll include the icon in the next update.

**Comment by sm4tik** [comment]
Awesome, TIA!
I'll try to remember to inform you if new icons pop up.
