### ISSUE TITLE
Can't remove Lockscreen wallpaper

### ISSUE THREAD

**Issue by jesuisfol** [gabrielelucci/greyscale-cmte#8]
With only Greyscale and System themes, there is no way (or I can't find any) to remove the lockscreen wallpaper.

There should be a way to revert to the System lockscreen. But I'm not sure this can be fixed by you however...
(I've tried to switch to the live lockscreen, and back again to the normal. However, the default lockscreen wallpaper isn't restored, just the Greyscale one)

**Comment by gabrielelucci** [comment]
Thank you for reporting.

It's a bug of the CMTE, it happens with every theme. Solution is a to remove the file 

/data/system/users/0/wallpaper_keyguard 

with file manager or recovery.

I'll remove the lock screen wallpaper in the next release (should be ready sometime this week), it's useless and causing this annoying problem. Also, I think it's a deprecated feature that will be soon replaced by the upcoming Live Lockscreen feature.

**Comment by jesuisfol** [comment]
Thank you !

I tried googling this "lockscreen wallpaper", without much success. I agree it looks like something deprecated :)
