### ISSUE TITLE
OnePlus2 notification slider setting

### ISSUE THREAD

**Issue by beschoenen** [gabrielelucci/greyscale-cmte#9]
I'm using the unofficial build posted by the maintainer.

[Settings list](https://i.xzq.be/f0f6cdd2cc.jpg)
[Setting](https://i.xzq.be/ef40b9140f.jpg)

**Comment by gabrielelucci** [comment]
Thank you for reporting. Can link me a thread/repo something about this build? 

All I found is [this](https://github.com/Grarak/android_device_oppo_common/commit/1637ef6c0176c15fc89fbce85b0466814eb2f3cf) and [this](https://github.com/CyanogenMod/android_device_oppo_common/commit/64f87201404147f1ce2922a20252879ecaf196d5), but I'm not sure it's what I'm looking for.

**Comment by beschoenen** [comment]
I got the link from his [twitter](https://twitter.com/Grarak).

**Comment by gabrielelucci** [comment]
Should be ok, I'll push a new version in Play Store. Let me know if it the icon is themed. 

https://github.com/gabrielelucci/greyscale-cmte/commit/e418880b9c7737fbdd0459c958401a93a3a42cbe

**Comment by beschoenen** [comment]
The icon looks good.

**Comment by gabrielelucci** [comment]
Yay! I'll try to theme settings page as well, but I couldn't figure it out as of now

**Comment by beschoenen** [comment]
Just FYI, the gestures page isn't themed either, not sure how it's different from other CM roms tho.
